// #include "ProtoWIBSuperChunkTypeAdapter.hpp"
// #include "DUNEWIBSuperChunkTypeAdapter.hpp"
// #include "DAPHNESuperChunkTypeAdapter.hpp"
// #include "TDEAMCFrameTypeAdapter.hpp"
// #include "SSPFrameTypeAdapter.hpp"
// #include "fdreadoutlibs/TriggerPrimitiveTypeAdapter.hpp"
#include "RawFWDUNEWIBTriggerPrimitiveSuperChunkTypeAdapter.hpp"
#include "VariableSizePayloadTypeAdapter.hpp"
